# Generated by Django 5.2.6 on 2025-12-03 14:47

import django.db.models.deletion
import emails.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.EmailField(max_length=254)),
                ('destinatario', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('email_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pendente', models.BooleanField(default=False)),
                ('erro_envio', models.TextField(blank=True, null=True)),
                ('email_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='emails.email')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=emails.models.anexos_email_upload_to)),
                ('caminhoArquivo', models.CharField(max_length=255)),
                ('tamanho', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='emails.email')),
            ],
        ),
    ]
