# Generated by Django 5.2.6 on 2025-12-06 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Pesquisador',
                'verbose_name_plural': 'Pesquisadores',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Projeto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('caae', models.CharField(help_text='Certificado de Apresentação para Apreciação Ética', max_length=254, unique=True, verbose_name='CAAE')),
                ('protocolo', models.CharField(blank=True, max_length=254, null=True, verbose_name='Protocolo')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='projetos/pdfs/', verbose_name='Arquivo do Projeto (PDF)')),
                ('data_submissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Submissão')),
                ('data_aprovacao', models.DateField(blank=True, help_text='Preenchido automaticamente ao aprovar.', null=True, verbose_name='Data de Aprovação')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em Análise'), ('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='novo', max_length=20)),
                ('rel_final', models.BooleanField(default=False, verbose_name='Relatório Final Recebido')),
                ('rel_parc', models.BooleanField(default=False, verbose_name='Relatório Parcial Recebido')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='core.pesquisador', verbose_name='Pesquisador Responsável')),
                ('relator_designado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_designados', to=settings.AUTH_USER_MODEL, verbose_name='Relator do Conselho')),
            ],
        ),
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_parecer', models.DateTimeField(auto_now_add=True, verbose_name='Data do Parecer')),
                ('decisao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], max_length=20)),
                ('justificativa', models.TextField()),
                ('relator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres_dados', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='core.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Emenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Emenda')),
                ('descricao', models.TextField(verbose_name='Descrição das Alterações')),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='emendas/pdfs/', verbose_name='Arquivo da Emenda (PDF)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada')], default='pendente', max_length=20, verbose_name='Status da Emenda')),
                ('data_parecer', models.DateTimeField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa do Parecer')),
                ('relator_parecer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emendas_avaliadas', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emendas', to='core.projeto')),
            ],
        ),
    ]
