# Generated by Django 5.2.6 on 2025-12-12 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parecer',
            name='data_parecer',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Parecer'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_submissao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Submissão'),
        ),
    ]
