# Generated by Django 5.2.6 on 2025-12-03 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='projetos/pdfs/', verbose_name='Arquivo do Projeto (PDF)'),
        ),
        migrations.CreateModel(
            name='Emenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Emenda')),
                ('descricao', models.TextField(verbose_name='Descrição das Alterações')),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='emendas/pdfs/', verbose_name='Arquivo da Emenda (PDF)')),
                ('aprovada', models.BooleanField(default=False, verbose_name='Emenda Aprovada?')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emendas', to='core.projeto')),
            ],
        ),
    ]
