# Generated by Django 5.2.6 on 2025-12-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_parecer_data_parecer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='arquivo_parecer',
            field=models.FileField(blank=True, null=True, upload_to='pareceres/pdfs/', verbose_name='Anexo do Parecer (PDF)'),
        ),
    ]
