# Generated by Django 5.2.6 on 2025-12-06 07:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_log', models.CharField(max_length=255)),
                ('processo', models.CharField(max_length=255)),
                ('parametros_usados', models.JSONField(default=dict, null=True)),
                ('horario', models.DateTimeField(default=django.utils.timezone.now)),
                ('concluiu', models.BooleanField(default=False)),
                ('msgErro', models.TextField(blank=True, null=True)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projeto')),
            ],
        ),
    ]
